export const ORPHANAGE_LIST_REQUEST = 'ORPHANAGE_LIST_REQUEST'
export const ORPHANAGE_LIST_SUCCESS = 'ORPHANAGE_LIST_SUCCESS'
export const ORPHANAGE_LIST_ERROR = 'ORPHANAGE_LIST_ERROR'

export const ORPHANAGE_ADD_REQUEST = 'ORPHANAGE_ADD_REQUEST'
export const ORPHANAGE_ADD_SUCCESS = 'ORPHANAGE_ADD_SUCCESS'
export const ORPHANAGE_ADD_ERROR = 'ORPHANAGE_ADD_ERROR'

export const ORPHANAGE_DETAILS_REQUEST = 'ORPHANAGE_DETAILS_REQUEST'
export const ORPHANAGE_DETAILS_SUCCESS = 'ORPHANAGE_DETAILS_SUCCESS'
export const ORPHANAGE_DETAILS_ERROR = 'ORPHANAGE_DETAILS_ERROR'

export const ORPHANAGE_UPDATE_REQUEST = 'ORPHANAGE_UPDATE_REQUEST'
export const ORPHANAGE_UPDATE_SUCCESS = 'ORPHANAGE_UPDATE_SUCCESS'
export const ORPHANAGE_UPDATE_ERROR = 'ORPHANAGE_UPDATE_ERROR'
export const ORPHANAGE_UPDATE_RESET = 'ORPHANAGE_UPDATE_RESET'

export const ORPHANAGE_DELETE_REQUEST = 'ORPHANAGE_DELETE_REQUEST'
export const ORPHANAGE_DELETE_SUCCESS = 'ORPHANAGE_DELETE_SUCCESS'
export const ORPHANAGE_DELETE_ERROR = 'ORPHANAGE_DELETE_ERROR'
export const ORPHANAGE_DELETE_RESET = 'ORPHANAGE_DELETE_RESET'
